name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      run: echo ${{secrets.DOCKER_HUB_TOKEN}} | docker login -u ${{secrets.DOCKER_HUB_USERNAME}} --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag evgenyk/phorge:latest
    - name: Push Docker image to registry
      run: docker push keugenek/phorge:latest
